apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro-livraria
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/houda2024/DevopsProject.git
    targetRevision: HEAD
    path: micro-livraria
  destination:
    server: https://kubernetes.default.svc
    namespace: micro-livraria