apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro-livraria
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/houda2024/micro-livraria.git
    targetRevision: main
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: micro-livraria
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
