apiVersion: v1
kind: Service
metadata:
  name: devopsprojectmicro-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: devopsprojectmicro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
