apiVersion: v1
kind: Service
metadata:
  name: devopsprojectmicro-nodeport
spec:
  type: NodePort
  selector:
    app: devopsprojectmicro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
